#!/usr/bin/env bash
# This script transfers a file to a remote server using SCP.
# It requires four arguments:
#   - PATH_TO_FILE: the local path to the file to be transferred
#   - IP: the IP address of the remote server
#   - USERNAME: the username for the remote server
#   - PATH_TO_SSH_KEY: (optional) the path to the SSH key for authentication

if [ $# -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
fi;

if [ $# -ge 4 ];
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi;
