#!/usr/bin/env bash

# Update the package repository
sudo apt-get -y update

# Install Nginx web server
sudo apt-get -y install nginx

# Allow incoming HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create index.html file with "Hello World" content
echo "Hello World" | sudo tee /var/www/html/index

# Add redirection rule to Nginx configuration
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
